In [ ]:
import pandas as pd,numpy as np,os,pickle
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.decomposition import TruncatedSVD
from sklearn.feature_extraction.text import TfidfVectorizer
from sentence_transformers import SentenceTransformer,util
from scipy.sparse import csr_matrix
from warnings import filterwarnings
from dotenv import load_dotenv
load_dotenv()
filterwarnings('ignore')
os.environ['HF_TOKEN']=os.getenv('HF_API_KEY')

In [170]:
df=pd.read_csv('Employees Job Desc\job_dataset.csv')
df.head()

       JobID  ...                                           Keywords
0  NET-F-001  ...  .NET; C#; ASP.NET MVC; Entity Framework; SQL S...
1  NET-F-002  ...  .NET; C#; ASP.NET MVC; Entity Framework; SQL S...
2  NET-F-003  ...  .NET; C#; ASP.NET MVC; SQL Server; Entity Fram...
3  NET-F-004  ...    .NET; C#; SQL Server; Entity Framework; ASP.NET
4  NET-F-005  ...  .NET; C#; ASP.NET MVC; Entity Framework; SQL S...

[5 rows x 7 columns]

In [171]:
df.isna().sum()

JobID                0
Title                1
ExperienceLevel      0
YearsOfExperience    0
Skills               0
Responsibilities     0
Keywords             0
dtype: int64

In [172]:
df[df.Title.isna()]

    JobID  ...                                           Keywords
36  AI017  ...  AI; ML; Senior-Level; Deep Learning; NLP; Clou...

[1 rows x 7 columns]

In [173]:
df.loc[df.Title.isna(),'Title']='Machine Learning Engineer'

In [174]:
df.Title.str.contains('Machine Learning Engineer',case=False).sum()

np.int64(9)

In [175]:
df.columns

Index(['JobID', 'Title', 'ExperienceLevel', 'YearsOfExperience', 'Skills',
       'Responsibilities', 'Keywords'],
      dtype='object')

In [176]:
df.Responsibilities.unique()

array(['Assist in coding and debugging applications; Learn and apply .NET Framework and Core fundamentals; Support team in building ASP.NET MVC web applications; Write basic SQL queries and work with Entity Framework; Collaborate with peers to solve issues; Participate in code reviews for learning; Follow best practices in coding; Work with version control (Git)',
       'Write simple C# programs under guidance; Support development of ASP.NET MVC applications; Implement Razor views and front-end logic; Assist in database query writing; Participate in unit testing tasks; Learn and apply LINQ for data operations; Work with mentors for code corrections',
       'Contribute to development of small modules; Assist in bug fixing and debugging; Learn and implement MVC patterns; Support database integration tasks; Understand version control basics; Work on minor testing scripts; Follow coding standards',
       ...,
       'Lead Vue.js front-end development; Integrate Node.js back-end services; Deploy applications on AWS using Docker; Implement caching strategies with Redis; Set up automated testing; Manage CI/CD pipelines',
       'Develop complex web applications; Integrate React front-end with Node.js back-end; Manage MongoDB database operations; Deploy with Docker/Kubernetes on AWS; Develop and integrate REST and GraphQL APIs; Optimize web performance',
       'Lead Angular front-end development; Develop Node.js back-end services; Optimize databases and caching; Deploy using Docker and AWS; Manage CI/CD pipelines; Ensure quality with automated testing'],
      shape=(1047,), dtype=object)

In [177]:
pd.crosstab(df['ExperienceLevel'],df['YearsOfExperience'])

YearsOfExperience   0  0-1  0-1 Years  0-2  ...  9  9+  9-12  9–12 years
ExperienceLevel                             ...
Entry-Level         0    0          0    0  ...  0   0     0           0
Experienced         0    0          0    0  ...  2   8     3           1
Fresher            48  242         10   25  ...  0   0     0           0
Junior              0    5          0    0  ...  0   0     0           0
Lead                0    0          0    0  ...  0   0     0           0
Mid-Level           0    0          0    0  ...  0   0     0           0
Mid-Senior          0    0          0    0  ...  0   0     0           0
Mid-Senior Level    0    0          0    0  ...  0   0     0           0
Mid-level           0    0          0    0  ...  0   0     0           0
Senior              0    0          0    0  ...  0   0     0           0
Senior-Level        0    0          0    0  ...  0   0     0           0

[11 rows x 110 columns]

In [178]:
df.YearsOfExperience.value_counts()

YearsOfExperience
0-1           247
0–1 year      104
5+             49
0              48
2-5            35
             ...
5–7 years       1
1–3 years       1
13-17           1
7–10 years      1
7-9             1
Name: count, Length: 110, dtype: int64

In [179]:
df['YearsOfExperience']=df['YearsOfExperience'].apply(lambda x:x.split(' ')[0].strip() if 'year' in x.lower() else x.lower().strip())
df['YearsOfExperience'].value_counts()

YearsOfExperience
0-1      257
0–1      104
5+        71
0         48
6+        36
        ...
13-17      1
7–9        1
8–10       1
9–12       1
7-9        1
Name: count, Length: 84, dtype: int64

In [180]:
df['YearsOfExperience']=df['YearsOfExperience'].str.extract(r'(\d+)\+?$|\D*(\d+)$').bfill(axis=1)[0].astype(int)
df['YearsOfExperience'].value_counts()

YearsOfExperience
1     361
5     155
10     81
6      79
8      58
7      54
0      48
4      47
3      41
9      35
2      31
12     23
15     18
11      7
16      6
13      6
20      6
14      5
17      4
18      3
Name: count, dtype: int64

In [181]:
pd.crosstab(df['ExperienceLevel'],df['YearsOfExperience'])

YearsOfExperience  0    1   2   3   4   5   6   ...  13  14  15  16  17  18  20
ExperienceLevel                                 ...
Entry-Level         0   66   0   0   0   0   0  ...   0   0   0   0   0   0   0
Experienced         0    0   6  41  42  98  43  ...   6   5  18   6   4   3   6
Fresher            48  290  25   0   0   0   0  ...   0   0   0   0   0   0   0
Junior              0    5   0   0   0   0   0  ...   0   0   0   0   0   0   0
Lead                0    0   0   0   0   0   0  ...   0   0   0   0   0   0   0
Mid-Level           0    0   0   0   0  44  13  ...   0   0   0   0   0   0   0
Mid-Senior          0    0   0   0   0   0   2  ...   0   0   0   0   0   0   0
Mid-Senior Level    0    0   0   0   0   0   2  ...   0   0   0   0   0   0   0
Mid-level           0    0   0   0   5   0   0  ...   0   0   0   0   0   0   0
Senior              0    0   0   0   0   6   4  ...   0   0   0   0   0   0   0
Senior-Level        0    0   0   0   0   7  15  ...   0   0   0   0   0   0   0

[11 rows x 20 columns]

In [182]:
df.Responsibilities[0]

'Assist in coding and debugging applications; Learn and apply .NET Framework and Core fundamentals; Support team in building ASP.NET MVC web applications; Write basic SQL queries and work with Entity Framework; Collaborate with peers to solve issues; Participate in code reviews for learning; Follow best practices in coding; Work with version control (Git)'

In [183]:
def tfidf_vectorizer(df):
    tfidf=TfidfVectorizer(stop_words='english')
    df['Combined_Text']=df['Title']+' '+df['Skills']+ ' '+df['Responsibilities']+' '+df['Keywords']
    tfidf_df=tfidf.fit_transform(df['Combined_Text'])
    return tfidf_df,tfidf
def tfidf_get_recommendations(job_title,req_skills,min_exp,df,n=5):
    filtered_df=df[df['YearsOfExperience']>=min_exp]
    if filtered_df.empty:
        return pd.DataFrame(columns=['Title','Skills','Responsibilities','Keywords','YearsOfExperience','Cosine_Score'])
    tfidf_df,tfidf=tfidf_vectorizer(filtered_df)
    request_text=f'{job_title} {req_skills}'
    request_tfidf=tfidf.transform([request_text])
    cos_scores=cosine_similarity(request_tfidf,tfidf_df).flatten()
    filtered_df['Cosine_Score']=cos_scores
    sorted_df=filtered_df.sort_values(by='Cosine_Score',ascending=False)
    return sorted_df[['Title','Skills','Responsibilities','Keywords','YearsOfExperience','Cosine_Score']].head(n)
tfidf_get_recommendations('Data Scientist','Python,SQL,JAVA, Machine Learning',3,df,n=5)

                               Title  ... Cosine_Score
349     Data Scientist - Experienced  ...     0.594711
352         Principal Data Scientist  ...     0.522903
353       Machine Learning Scientist  ...     0.496263
355  Lead Machine Learning Scientist  ...     0.474289
350            Senior Data Scientist  ...     0.407134

[5 rows x 6 columns]

In [184]:
df.head()

       JobID  ...                                           Keywords
0  NET-F-001  ...  .NET; C#; ASP.NET MVC; Entity Framework; SQL S...
1  NET-F-002  ...  .NET; C#; ASP.NET MVC; Entity Framework; SQL S...
2  NET-F-003  ...  .NET; C#; ASP.NET MVC; SQL Server; Entity Fram...
3  NET-F-004  ...    .NET; C#; SQL Server; Entity Framework; ASP.NET
4  NET-F-005  ...  .NET; C#; ASP.NET MVC; Entity Framework; SQL S...

[5 rows x 7 columns]

In [186]:
sent_model=SentenceTransformer('all-MiniLM-L6-v2')
def generate_embeddings(df,sent_model):
    df['Combined_Text']=df['Title']+' '+df['Skills']+ ' '+df['Responsibilities']+' '+df['Keywords']
    embeddings=sent_model.encode(df['Combined_Text'].tolist(),convert_to_tensor=True)
    return embeddings
def transformer_recommendations(job_title,req_skills,min_exp,df,sent_model,n=5):
    request_text=f'{job_title} {req_skills}'
    request_embedding=sent_model.encode(request_text,convert_to_tensor=True)
    embeddings=generate_embeddings(df,sent_model)
    cos_scores=util.cos_sim(request_embedding,embeddings).reshape(-1,1)
    df['Cosine_Score_Sentence_Transformer']=cos_scores.cpu().numpy()
    filtered_df=df[df['YearsOfExperience']>=min_exp]
    filtered_df=filtered_df.sort_values(by='Cosine_Score_Sentence_Transformer',ascending=False)
    return filtered_df[['Title','Skills','Responsibilities','Keywords','YearsOfExperience','Cosine_Score_Sentence_Transformer']].head(n)
transformer_recommendations('Data Scientist','Python,SQL,JAVA, Machine Learning',3,df,sent_model,n=5)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 6034.63it/s]

                            Title  ... Cosine_Score_Sentence_Transformer
349  Data Scientist - Experienced  ...                          0.742001
352      Principal Data Scientist  ...                          0.735376
356        Data Science Team Lead  ...                          0.711222
350         Senior Data Scientist  ...                          0.703446
351           Lead Data Scientist  ...                          0.693424

[5 rows x 6 columns]

In [ ]:
df['Transformer_Embeddings'] = list(generate_embeddings(df, sent_model).cpu().numpy())
tfidf_matrix, trained_tfidf = tfidf_vectorizer(df)
session_data = {
    'dataframe': df,
    'tfidf_vectorizer': trained_tfidf,
    'tfidf_matrix': tfidf_matrix
    }
with open('search_assets.pkl', 'wb') as f:
    pickle.dump(session_data, f)
print("Assets saved successfully!")

Assets saved successfully!

In [187]:
with open('search_assets.pkl', 'rb') as f:
    assets=pickle.load(f)
loaded_df=assets['dataframe']
trained_tfidf=assets['tfidf_vectorizer']
tfidf_matrix=assets['tfidf_matrix']
query='Data Scientist Python SQL JAVA Machine Learning'
query_vector=trained_tfidf.transform([query])
cosine_similarities=cosine_similarity(query_vector,tfidf_matrix).flatten()

In [188]:
cosine_similarities_df=pd.DataFrame({'Index':range(len(cosine_similarities)),'Cosine_Similarity':cosine_similarities})
cosine_similarities_df=cosine_similarities_df.sort_values(by='Cosine_Similarity',ascending=False)
cosine_similarities_df=pd.merge(cosine_similarities_df,loaded_df,left_on='Index',right_index=True)
if cosine_similarities_df.empty:
    print("No matching job descriptions found.")
cosine_similarities_df=cosine_similarities_df[cosine_similarities_df['YearsOfExperience']>=3]
cosine_similarities_df=cosine_similarities_df[['Title','Skills','Responsibilities','Keywords','YearsOfExperience','Cosine_Similarity']]
cosine_similarities_df.head()

                               Title  ... Cosine_Similarity
349     Data Scientist - Experienced  ...          0.594726
352         Principal Data Scientist  ...          0.512933
353       Machine Learning Scientist  ...          0.498019
355  Lead Machine Learning Scientist  ...          0.465896
350            Senior Data Scientist  ...          0.395272

[5 rows x 6 columns]

In [196]:
print(transformer_recommendations('Data Scientist','Python,SQL,JAVA, Machine Learning',3,loaded_df,sent_model,n=5))
%timeit

                            Title  ... Cosine_Score_Sentence_Transformer
349  Data Scientist - Experienced  ...                          0.742001
352      Principal Data Scientist  ...                          0.735376
356        Data Science Team Lead  ...                          0.711222
350         Senior Data Scientist  ...                          0.703446
351           Lead Data Scientist  ...                          0.693424

[5 rows x 6 columns]

In [ ]:
def get_semantic_recommendations(job_title, req_skills, min_exp, df, sent_model, n=5):
    filtered_df = df[df['YearsOfExperience'] >= min_exp]
    if filtered_df.empty:
        return pd.DataFrame(columns=['Title', 'Skills', 'Responsibilities', 'Keywords', 'YearsOfExperience', 'Transformer_Score'])
    request_text = f'{job_title} {req_skills}'
    query_embedding = sent_model.encode([request_text]).reshape(1, -1)
    dataset_embeddings = np.vstack(filtered_df['Transformer_Embeddings'].values)
    cos_scores = cosine_similarity(dataset_embeddings, query_embedding).flatten()
    filtered_df['Transformer_Score'] = cos_scores
    sorted_df = filtered_df.sort_values(by='Transformer_Score', ascending=False)
    
    return sorted_df[['Title', 'Skills', 'Responsibilities', 'Keywords', 'YearsOfExperience', 'Transformer_Score']].head(n)
print(get_semantic_recommendations('Data Scientist', 'Python, SQL, JAVA, Machine Learning', 3, loaded_df, sent_model, n=5))

                            Title  ... Transformer_Score
349  Data Scientist - Experienced  ...          0.742001
352      Principal Data Scientist  ...          0.735376
356        Data Science Team Lead  ...          0.711222
350         Senior Data Scientist  ...          0.703446
351           Lead Data Scientist  ...          0.693424

[5 rows x 6 columns]

In [210]:
request_text = 'Data Scientist Python, SQL, JAVA, Machine Learning'
query_embedding = sent_model.encode([request_text]).flatten().reshape(1, -1)
np.vstack(loaded_df['Transformer_Embeddings']).shape

(1068, 384)

In [211]:
print(query_embedding.shape)
print(query_embedding)

(1, 384)
[[-5.70228212e-02 -4.67442758e-02  7.83364754e-03  6.38439134e-02
  -3.82725149e-02 -1.50322929e-01  1.91070549e-02  1.39356125e-04
  -1.59663171e-01 -3.21988426e-02 -7.22165257e-02 -2.34680753e-02
   4.95439656e-02 -1.81102492e-02  6.37137564e-03  6.73172101e-02
  -8.95320401e-02  1.40379267e-02  2.25619096e-02 -1.13402240e-01
  -7.57243782e-02 -1.21908626e-02  1.83357280e-02 -2.35558432e-02
   8.98371115e-02  1.95953697e-02  6.82219192e-02  4.00113687e-02
  -6.35271594e-02 -7.11900648e-03 -9.69707519e-02 -2.04455629e-02
  -3.39813419e-02  2.14217082e-02 -6.10835925e-02 -2.10197680e-02
   1.99269168e-02  1.06468182e-02 -1.70992818e-02  1.50077287e-02
  -4.51910794e-02 -4.21433933e-02  8.73133540e-03 -1.64323987e-03
   3.81005020e-03  1.24749579e-02 -4.08114158e-02 -4.58165295e-02
  -3.10454750e-03  5.08274045e-03 -1.52959555e-01 -3.63845825e-02
  -2.18682438e-02 -3.30158994e-02 -2.51372973e-03  2.48559862e-02
   6.91573918e-02  1.16455099e-02 -3.16114537e-02 -1.02936447e-01
  -6.90552816e-02 -5.79423234e-02 -4.11674753e-02  4.79203984e-02
  -2.46245507e-03 -3.73837091e-02  6.21083527e-05  4.99145649e-02
   6.25956059e-02 -6.89495131e-02 -6.91925064e-02  1.66772529e-02
  -6.89151511e-02  8.09578076e-02  4.65530865e-02 -2.40221806e-02
   3.83410566e-02  2.05032667e-03  7.91055635e-02  1.35226194e-02
  -1.58473514e-02 -5.28478287e-02 -1.20477647e-01  1.11350626e-01
   2.35625952e-02 -9.45077166e-02 -9.90125444e-03  9.21047479e-02
  -4.15868908e-02  8.21627583e-03  9.20663774e-02 -5.01027144e-02
   5.84097691e-02  1.57191996e-02 -7.52518997e-02  8.03420097e-02
  -4.42228578e-02 -6.65184334e-02  5.38902618e-02  4.69753705e-02
  -2.52972823e-02  1.96110830e-02 -3.06534162e-03  4.45630141e-02
   3.38277817e-02  3.82309034e-02  4.47031744e-02 -8.34785476e-02
   1.10019714e-01 -2.26997808e-02 -2.40967497e-02  2.32475367e-03
  -2.25310717e-02 -6.73928186e-02 -8.39803461e-03  3.16282287e-02
  -2.19747797e-02  5.18514626e-02  6.78310171e-04  5.20491824e-02
  -6.57892525e-02  5.54189160e-02 -5.66283092e-02 -3.18055637e-02
   2.69810800e-02  3.60392556e-02 -1.18474171e-01 -1.77052849e-33
   5.64663380e-04 -4.81694750e-02  8.00272822e-02 -6.29916340e-02
   5.31647839e-02 -7.87067637e-02 -1.65468489e-03  1.98988859e-02
  -2.55417055e-03 -9.94173903e-03 -3.47271003e-02  9.21098143e-02
  -2.91026421e-02  1.55377407e-02  6.08795322e-02  1.42372651e-02
   4.47997823e-02  6.64172396e-02 -3.85212898e-02  3.64014581e-02
   6.77247345e-02 -1.09899398e-02  4.42829579e-02  6.13454469e-02
  -8.84631998e-04  1.87798087e-02 -5.62808360e-04  3.69293429e-02
   3.29113007e-02  6.76270649e-02 -3.56913283e-02 -6.92046061e-02
  -7.04277009e-02  5.11840396e-02  5.63557930e-02 -2.03933045e-02
  -4.15013917e-02 -5.46144135e-02  6.45466149e-02 -7.39027048e-04
  -9.67228487e-02 -5.15191862e-03  5.45142442e-02 -1.10922530e-02
  -6.06807210e-02  6.55687694e-03  3.03698611e-02 -3.74624529e-03
  -9.83292423e-03  3.57933156e-02 -2.69611981e-02 -9.99395773e-02
   3.77321020e-02  4.84591462e-02  2.36074701e-02  1.06566466e-01
   4.75924611e-02 -7.99748464e-04 -3.49368341e-02 -6.65042317e-03
  -5.15476912e-02  4.27780263e-02  5.22720292e-02 -6.70259073e-02
  -1.01286499e-02  7.28076398e-02  1.89978089e-02  9.44907311e-03
   4.48305421e-02 -1.85308693e-06  2.31632218e-02  3.57681662e-02
   2.08317153e-02 -3.04577593e-02  2.42315326e-02  2.29435265e-02
   4.83082384e-02 -5.52919768e-02  2.29137801e-02  6.21906295e-02
   1.15555525e-02  4.20494657e-03 -5.27353399e-03 -3.07549834e-02
  -4.12662178e-02  7.51501694e-03  2.99412739e-02  2.68962402e-02
  -2.91506834e-02  1.88442133e-02 -8.30933899e-02  3.86824720e-02
   3.64161767e-02  7.54597364e-03 -3.43811885e-02  3.94464726e-34
  -5.70807420e-02  1.90056339e-02 -2.43540742e-02  5.81188463e-02
   2.57113650e-02  1.81015339e-02 -2.81900670e-02 -3.08530573e-02
   4.71841581e-02 -2.87292004e-02 -3.03915180e-02 -5.78549653e-02
   8.36750567e-02  3.63677144e-02  2.44793817e-02  7.10076466e-02
  -6.97649792e-02  6.24496816e-03 -5.38729243e-02  7.33079687e-02
  -2.39169877e-02  1.47298425e-01 -7.85899460e-02 -7.66706245e-04
   3.03903483e-02 -6.43321946e-02 -2.67423857e-02 -2.39433460e-02
  -9.95593239e-03  7.23840073e-02 -4.76029236e-03  2.51311325e-02
  -5.70108034e-02 -5.75899482e-02  6.34947196e-02 -3.23315561e-02
   2.45661270e-02 -6.97452053e-02  4.28556055e-02  3.77559811e-02
   6.49878234e-02  4.51500602e-02  5.00179036e-03  4.12618928e-02
   1.99329779e-02 -2.11466756e-02 -4.81482521e-02  8.57071802e-02
   2.84428205e-02 -7.01675117e-02 -2.21381313e-03  1.67843886e-02
   1.86587255e-02 -3.58263552e-02  1.94494613e-02 -7.21044853e-05
   5.62138818e-02  1.04895858e-02 -9.15272906e-02  5.05059771e-02
  -1.14499539e-01 -4.80883196e-03  9.93710011e-02  5.54444827e-02
  -4.85904105e-02  6.38799146e-02 -3.94077674e-02  5.00120148e-02
  -8.07459727e-02 -1.08042710e-01  2.10526735e-02  9.66042839e-03
   4.31545265e-02 -3.39387392e-04 -2.30550356e-02  4.36981097e-02
  -9.85617116e-02 -1.42941214e-02 -7.35384226e-02  8.06650594e-02
   6.96814060e-02 -2.54153144e-02 -3.33918408e-02  5.92817999e-02
  -3.23190279e-02  5.64310178e-02  2.59072855e-02 -2.68789306e-02
  -3.23806107e-02 -1.15646735e-01 -5.65706491e-02  3.34649421e-02
  -4.53401916e-02  2.70346403e-02 -1.91860441e-02 -1.46258259e-08
   4.16525230e-02  7.54812872e-03  7.48864785e-02 -6.66468032e-03
   1.04271352e-01  4.25725728e-02 -1.04169436e-01  1.40716195e-01
  -2.69740373e-02  7.91921616e-02  5.00429645e-02  5.85053787e-02
  -3.97755532e-03 -4.41990141e-03 -1.49966227e-02  7.98294097e-02
   4.64053936e-02 -1.95039138e-02 -4.68452573e-02  4.51395400e-02
   8.14084411e-02  1.40392752e-02 -3.69575247e-02  4.93297242e-02
  -1.08475024e-02 -7.60953575e-02 -2.70537492e-02 -1.11795478e-02
   6.59472076e-03 -1.62975676e-02 -3.59334499e-02 -3.07198837e-02
  -1.29631790e-03 -4.44281138e-02  5.00313379e-02 -2.11085379e-02
   8.17652270e-02 -5.64908087e-02 -5.64011596e-02  3.95460092e-02
  -1.44078992e-02  2.99860444e-02 -2.25948319e-02  3.82909141e-02
   2.69453544e-02  4.25309241e-02  6.41480042e-03  1.43608795e-02
   2.19444395e-03 -1.36592146e-03 -4.02619597e-03 -1.80841573e-02
  -1.86248776e-02 -3.52733843e-02  8.86408985e-02  5.20887524e-02
  -1.52734248e-02  1.59331539e-03 -4.36663628e-02  3.60265411e-02
   2.19944231e-02  1.53394360e-02  9.92775112e-02  2.05055997e-02]]